(console.log (map [ 1 2 3 ] +1)
             (map [ 1 2 3 ] --1)
             (map [ 1 2 3 ] *2)
             (map [ 1 2 3 ] /2)
             (map [ 1 2 3 ] ^2))

(console.log (format "(~~) (~~) (~~)" [ 1 2 3 ] ))
(console.log (format "(~foo~) (~bar~)" { bar 7 foo 8 } ))
(console.log (reduce [ "foo" "bar" "baz" ] cat))
(console.log ((map [1 null "foo" [1 2 3] {} NaN (re "foo") undefined nop] type).join ","))
(console.log ((map [1 "foo" [1 2 3] {} NaN (re "foo")] string).join ","))
(console.log ((# (f) (f "1 2 3 4 5" (re "\d" "g") "x")) replace))
(console.log ((# (f) (f [ ])) size))
(console.log (select [ 1 -2 7 0 -3 9 ] positive?))
(console.log (select [ 1 -2 7 0 -3 9 ] non-negative?))
