(var x (random-float))
(var y (map (range (+1 (random-integer 10))) random-float))
(var joined (cons x y))
(console.log (= (car joined) x)
			 (isEqual (cdr joined) y)
			 (= (cadr joined) (car y)))
(var arr (map (range (+1 (random-integer 10)))
			  (# () [ (random-float) (random-float) ] )))
(console.log (isEqual (map arr cadr) (pluck arr 1))
			 (isEqual (map arr car) (pluck arr 0)))